settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: KennethLiu-Blog
    name: KennethLiu-Blog
    description: 'Blog Page'
    url: 'https://kennethliu.tk'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: Alist 
    name: Alist
    url: 'https://cn-hk.btl.moe:5244'
    method: GET
    expectStatus: 200
    linkable: true 
    
  - id: Azure E5 
    name: Azure E5
    url: 'https://cn-hk.btl.moe:1066'
    method: GET
    expectStatus: 200
    linkable: true 

  - id: ORACLE-US
    name: ORACLE-US
    url: 'https://us.btlcraft.top'
    method: GET
    expectStatus: 502
    linkable: false 

  - id: AWS-HK
    name: AWS-HK
    url: 'https://cn-hk.btl.moe'
    method: GET
    expectStatus: 502
    linkable: false 
  
  
